# app.yaml

runtime: python39
env: standard
entrypoint: gunicorn -b :$PORT collab_project.wsgi:application

handlers:
- url: /static              # new
  static_dir: staticfiles/  # new
- url: /media               # new
  static_dir: mediafiles/   # new
- url: /.*
  script: auto

runtime_config:
  python_version: 3

