# Generated by Django 4.2 on 2023-05-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("collab_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todoitem",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
